title: [inset blog title]
email: [insert contact email]

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog

url: [insert url here]
twitter_username: [insert username]
github_username:  [insert username]

font-url: 'https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700'

# Build settings
markdown: kramdown
timezone: [insert timezone here with Region/Country template] #insert template link
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib', 'vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
author: [insert name here]
plugins:
  - jekyll-feed
sass:
  style: compressed

# social profiles
social:
  - profile: facebook
    url: ''
    icon: 'fab fa-facebook-f'
  - profile: twitter
    url: ''
    icon: 'fab fa-twitter'
  - profile: instagram
    url: ''
    icon: 'fab fa-instagram'
