title: The Kendric Blog
email: ngkendric@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.kendric.blog
twitter_username: kendricng
github_username:  kenterminator

theme_color: black
# Build settings
markdown: kramdown
timezone: Asia/Hong_Kong
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib', 'vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
author: Kendric Ng
plugins:
  - jekyll-feed
sass:
  style: compressed
